--
-- PostgreSQL database dump
--

-- Dumped from database version 14.17 (Debian 14.17-1.pgdg120+1)
-- Dumped by pg_dump version 14.17 (Debian 14.17-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Clusters; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Clusters" (
    "Id" integer NOT NULL,
    "Name" character varying(30) NOT NULL,
    "ParentId" integer NOT NULL,
    "Products" integer[] NOT NULL
);


ALTER TABLE public."Clusters" OWNER TO postgres;

--
-- Name: Clusters_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Clusters" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Clusters_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: search_cluster; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.search_cluster (
    "Id" integer NOT NULL,
    "KeyWord" text NOT NULL,
    "ClusterId" integer NOT NULL
);


ALTER TABLE public.search_cluster OWNER TO postgres;

--
-- Name: search_cluster_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.search_cluster ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."search_cluster_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: Clusters; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Clusters" ("Id", "Name", "ParentId", "Products") FROM stdin;
\.


--
-- Data for Name: search_cluster; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.search_cluster ("Id", "KeyWord", "ClusterId") FROM stdin;
\.


--
-- Name: Clusters_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Clusters_Id_seq"', 1, true);


--
-- Name: search_cluster_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."search_cluster_Id_seq"', 1, false);


--
-- Name: Clusters PK_Clusters; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Clusters"
    ADD CONSTRAINT "PK_Clusters" PRIMARY KEY ("Id");


--
-- Name: search_cluster PK_search_cluster; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.search_cluster
    ADD CONSTRAINT "PK_search_cluster" PRIMARY KEY ("Id");


--
-- PostgreSQL database dump complete
--

