--
-- PostgreSQL database dump
--

-- Dumped from database version 14.17 (Debian 14.17-1.pgdg120+1)
-- Dumped by pg_dump version 14.17 (Debian 14.17-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: CommentReplies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CommentReplies" (
    "Id" integer NOT NULL,
    text character varying(400) NOT NULL,
    is_deleted boolean NOT NULL,
    id_comment integer NOT NULL
);


ALTER TABLE public."CommentReplies" OWNER TO postgres;

--
-- Name: CommentReplies_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CommentReplies" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CommentReplies_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Comments" (
    "Id" integer NOT NULL,
    estimation numeric NOT NULL,
    "Text" character varying(400) NOT NULL,
    date_created timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL,
    reply_id integer NOT NULL,
    user_name text NOT NULL,
    shop_id integer NOT NULL,
    id_product integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public."Comments" OWNER TO postgres;

--
-- Name: Comments_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Comments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Comments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Ratings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Ratings" (
    "RatingId" integer NOT NULL,
    average_rating numeric NOT NULL,
    amount_of_comments integer NOT NULL,
    "ProductID" integer
);


ALTER TABLE public."Ratings" OWNER TO postgres;

--
-- Name: Ratings_RatingId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Ratings" ALTER COLUMN "RatingId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Ratings_RatingId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: CommentReplies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CommentReplies" ("Id", text, is_deleted, id_comment) FROM stdin;
1	Новый комментарий исправленый	t	1
\.


--
-- Data for Name: Comments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Comments" ("Id", estimation, "Text", date_created, is_deleted, reply_id, user_name, shop_id, id_product, user_id) FROM stdin;
1	4	Новый комментарий	2025-05-26 12:54:13.38573+00	t	1	name	1	1	1
\.


--
-- Data for Name: Ratings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Ratings" ("RatingId", average_rating, amount_of_comments, "ProductID") FROM stdin;
1	-1	0	\N
\.


--
-- Name: CommentReplies_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."CommentReplies_Id_seq"', 1, true);


--
-- Name: Comments_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Comments_Id_seq"', 1, true);


--
-- Name: Ratings_RatingId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Ratings_RatingId_seq"', 1, true);


--
-- Name: CommentReplies PK_CommentReplies; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CommentReplies"
    ADD CONSTRAINT "PK_CommentReplies" PRIMARY KEY ("Id");


--
-- Name: Comments PK_Comments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Comments"
    ADD CONSTRAINT "PK_Comments" PRIMARY KEY ("Id");


--
-- Name: Ratings PK_Ratings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Ratings"
    ADD CONSTRAINT "PK_Ratings" PRIMARY KEY ("RatingId");


--
-- Name: IX_Comments_reply_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Comments_reply_id" ON public."Comments" USING btree (reply_id);


--
-- Name: Comments FK_Comments_CommentReplies_reply_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Comments"
    ADD CONSTRAINT "FK_Comments_CommentReplies_reply_id" FOREIGN KEY (reply_id) REFERENCES public."CommentReplies"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

