--
-- PostgreSQL database dump
--

-- Dumped from database version 14.18 (Debian 14.18-1.pgdg120+1)
-- Dumped by pg_dump version 14.18 (Debian 14.18-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ManagersShops; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ManagersShops" (
    "Id" integer NOT NULL,
    shop_id integer NOT NULL,
    user_id integer NOT NULL,
    role_user character varying(100) NOT NULL
);


ALTER TABLE public."ManagersShops" OWNER TO postgres;

--
-- Name: ManagersShops_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ManagersShops" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ManagersShops_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: ManagersShops; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ManagersShops" ("Id", shop_id, user_id, role_user) FROM stdin;
1	0	1	Administrator
2	0	1	Administrator
3	0	1	Administrator
4	0	1	Administrator
5	0	1	Administrator
6	0	1	Administrator
7	0	1	Administrator
8	0	1	Administrator
\.


--
-- Name: ManagersShops_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ManagersShops_Id_seq"', 8, true);


--
-- Name: ManagersShops PK_ManagersShops; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ManagersShops"
    ADD CONSTRAINT "PK_ManagersShops" PRIMARY KEY ("Id");


--
-- PostgreSQL database dump complete
--

