--
-- PostgreSQL database dump
--

-- Dumped from database version 14.17 (Debian 14.17-1.pgdg120+1)
-- Dumped by pg_dump version 14.17 (Debian 14.17-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: shop; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shop (
    id integer NOT NULL,
    name character varying(60) NOT NULL,
    is_delete boolean NOT NULL,
    description text NOT NULL,
    contact_info text NOT NULL,
    adress text NOT NULL,
    "Products" integer[] NOT NULL
);


ALTER TABLE public.shop OWNER TO postgres;

--
-- Name: shop_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shop ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: shop; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shop (id, name, is_delete, description, contact_info, adress, "Products") FROM stdin;
1	12	f				{}
2	1212	f	adsdas	12		{}
3	12231dsfdsfsdsfd	f	12	вфы		{}
4	12ddsdsdsf	f	sa12	3223		{}
5	sdsfdsfdsfdsf	f	dsfdasfasffdsa	dsfsdaasfd		{}
6	1221wadasdas	f	dasdasc	vczxvczxvc		{}
7	dasfdsf	f	12	dsadsf		{}
8	dsffdsdsf	f	dsfds	12132	dsfdsfdsf	{}
9	выавы	f	выавыавыаыав	выавыавыа	211212	{}
10	dsf	f	dsfdsf	2312	dsfdsf	{}
11	gdgfg	f	dgfssgfd	fddsfdgf	12432324	{}
\.


--
-- Name: shop_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shop_id_seq', 11, true);


--
-- Name: shop PK_shop; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop
    ADD CONSTRAINT "PK_shop" PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

