version: '3.8'

services:
  postgres1:
    image: postgres:14
    container_name: postgres1
    environment:
      POSTGRES_USER: admin1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: db1
    ports:
      - "5432:5432"  # Первая БД на стандартном порту
    volumes:
      - postgres_data1:/var/lib/postgresql/data

  postgres2:
    image: postgres:14
    container_name: postgres2
    environment:
      POSTGRES_USER: admin2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: db2
    ports:
      - "5433:5432"  # Вторая БД на порту 5433
    volumes:
      - postgres_data2:/var/lib/postgresql/data

  postgres3:
    image: postgres:14
    container_name: postgres3
    environment:
      POSTGRES_USER: admin3
      POSTGRES_PASSWORD: password3
      POSTGRES_DB: db3
    ports:
      - "5434:5432"  # Третья БД на порту 5434
    volumes:
      - postgres_data3:/var/lib/postgresql/data

  postgres4:
    image: postgres:14
    container_name: postgres4
    environment:
      POSTGRES_USER: admin4
      POSTGRES_PASSWORD: password4
      POSTGRES_DB: db4
    ports:
      - "5435:5432"  # Четвертая БД на порту 5435
    volumes:
      - postgres_data4:/var/lib/postgresql/data

  postgres5:
    image: postgres:14
    container_name: postgres5
    environment:
      POSTGRES_USER: admin5
      POSTGRES_PASSWORD: password5
      POSTGRES_DB: db5
    ports:
      - "5436:5432"  # Пятая БД на порту 5436
    volumes:
      - postgres_data5:/var/lib/postgresql/data

volumes:
  postgres_data1:
  postgres_data2:
  postgres_data3:
  postgres_data4:
  postgres_data5: