version: '3.8'

services:
  postgres1:
    image: ilyagall01/product-service2:latest1
    container_name: Products_bd_5000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: ProductsService
    ports:
      - "5000:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data
      - ./dumps/products_dump.sql:/docker-entrypoint-initdb.d/products_init.sql

  postgres2:
    image: ilyagall01/product-service2:latest1
    container_name: Shop_bd_5001
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: ShopService
    ports:
      - "5001:5432"
    volumes:
      - postgres_data1:/var/lib/postgresql/data
      - ./dumps/shop_dump.sql:/docker-entrypoint-initdb.d/shop_init.sql

  postgres3:
    image: ilyagall01/product-service2:latest1
    container_name: Favorite_bd_5002
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password3
      POSTGRES_DB: FavoriteService
    ports:
      - "5002:5432"
    volumes:
      - postgres_data3:/var/lib/postgresql/data
      - ./dumps/favorite_dump.sql:/docker-entrypoint-initdb.d/favorite_init.sql

  postgres4:
    image: ilyagall01/product-service2:latest1
    container_name: Comment_bd_5003
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password4
      POSTGRES_DB: CommentService
    ports:
      - "5003:5432"
    volumes:
      - postgres_data4:/var/lib/postgresql/data
      - ./dumps/comment_dump.sql:/docker-entrypoint-initdb.d/comment_init.sql

  postgres5:
    image: ilyagall01/product-service2:latest1
    container_name: Cluster_bd_5004
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password5
      POSTGRES_DB: ClusterService
    ports:
      - "5004:5432"
    volumes:
      - postgres_data5:/var/lib/postgresql/data
      - ./dumps/cluster_dump.sql:/docker-entrypoint-initdb.d/cluster_init.sql

volumes:
  postgres_data1:
  postgres_data2:
  postgres_data3:
  postgres_data4:
  postgres_data5: