version: '3.8'

services:
  postgres1:
    image: postgres:14
    container_name: ShopService_5001
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: ShopService
    ports:
      - "5001:5432"  # Первая БД на стандартном порту # нельзя на стандартном порту
    volumes:
      - postgres_data1:/var/lib/postgresql/data

  postgres2:
    image: postgres:14
    container_name: ProductsService_5000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: ProductsService
    ports:
      - "5000:5432"  # Вторая БД на порту 5000
    volumes:
      - postgres_data2:/var/lib/postgresql/data

  postgres3:
    image: postgres:14
    container_name: FavoriteService_5002
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password3
      POSTGRES_DB: FavoriteService
    ports:
      - "5002:5432"  # Третья БД на порту 5002
    volumes:
      - postgres_data3:/var/lib/postgresql/data

  postgres4:
    image: postgres:14
    container_name: CommentService_5003
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password4
      POSTGRES_DB: CommentService
    ports:
      - "5003:5432"  # Четвертая БД на порту 5435
    volumes:
      - postgres_data4:/var/lib/postgresql/data

  postgres5:
    image: postgres:14
    container_name: ClusterService_5004
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password5
      POSTGRES_DB: ClusterService
    ports:
      - "5004:5432"  # Пятая БД на порту 5436
    volumes:
      - postgres_data5:/var/lib/postgresql/data


  postgres6:
    image: postgres:14
    container_name: AuthService_5005
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password6
      POSTGRES_DB: AuthService
    ports:
      - "5005:5432"  # Пятая БД на порту 5436
    volumes:
      - postgres_data5:/var/lib/postgresql/data

  postgres7:
    image: postgres:14
    container_name: OwnerShop_5006
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password7
      POSTGRES_DB: OwnerShop
    ports:
      - "5006:5432"  # Пятая БД на порту 5436
    volumes:
      - postgres_data5:/var/lib/postgresql/data

volumes:
  postgres_data1:
  postgres_data2:
  postgres_data3:
  postgres_data4:
  postgres_data5:
  postgres_data6:
  postgres_data7:
