version: '3.8'

services:
  postgres1:
    image: postgres:14
    container_name: ShopService_5001
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: ShopService
    ports:
      - "5001:5432"  # Первая БД на стандартном порту # нельзя на стандартном порту
    volumes:
      - postgres_data1:/var/lib/postgresql/data

  postgres2:
    image: postgres:14
    container_name: ProductsService_5000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: ProductsService
    ports:
      - "5000:5432"  # Вторая БД на порту 5000
    volumes:
      - postgres_data2:/var/lib/postgresql/data

  postgres3:
    image: postgres:14
    container_name: FavoriteService_5002
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password3
      POSTGRES_DB: FavoriteService
    ports:
      - "5002:5432"  # Третья БД на порту 5002
    volumes:
      - postgres_data3:/var/lib/postgresql/data

  postgres4:
    image: postgres:14
    container_name: CommentService_5003
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password4
      POSTGRES_DB: CommentService
    ports:
      - "5003:5432"  # Четвертая БД на порту 5435
    volumes:
      - postgres_data4:/var/lib/postgresql/data

  postgres5:
    image: postgres:14
    container_name: ClusterService_5004
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password5
      POSTGRES_DB: ClusterService
    ports:
      - "5004:5432"  # Пятая БД на порту 5436
    volumes:
      - postgres_data5:/var/lib/postgresql/data
  # PGAdmin сервис
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres_network
    depends_on:
      - postgres1
      - postgres2
      - postgres3
      - postgres4
      - postgres5

volumes:
  postgres_data1:
  postgres_data2:
  postgres_data3:
  postgres_data4:
  postgres_data5:
  pgadmin_data:

networks:
  postgres_network:
    driver: bridge